### PR TITLE
Fix logging calls

### PR DESCRIPTION
**Pull request by zeisss**
go-logging changed their API. Updating to be master compatible.

### CODE REVIEW

**Comment by zeisss** [comment]
ping @giantswarm/cena 

I tried building `instance-api`, which uses `middleware-server`, which uses this. I got this error:

```
Refreshing cache of github.com/giantswarm/middleware-server
go get github.com/giantswarm/middleware-server
2016/03/09 14:17:56 Go get failed: The following command failed:

    go get github.com/giantswarm/middleware-server

Output of stderr was:

    # github.com/giantswarm/request-context
../../../.giantswarm/builder/cache/14eb32df9ec9ce22ac07efbc16c3309d22a98715/src/github.com/giantswarm/request-context/request_context.go:81: too many arguments in call to l.logger.Critical
../../../.giantswarm/builder/cache/14eb32df9ec9ce22ac07efbc16c3309d22a98715/src/github.com/giantswarm/request-context/request_context.go:97: too many arguments in call to l.logger.Warning
../../../.giantswarm/builder/cache/14eb32df9ec9ce22ac07efbc16c3309d22a98715/src/github.com/giantswarm/request-context/request_context.go:105: too many arguments in call to l.logger.Notice
../../../.giantswarm/builder/cache/14eb32df9ec9ce22ac07efbc16c3309d22a98715/src/github.com/giantswarm/request-context/request_context.go:113: too many arguments in call to l.logger.Info
../../../.giantswarm/builder/cache/14eb32df9ec9ce22ac07efbc16c3309d22a98715/src/github.com/giantswarm/request-context/request_context.go:121: too many arguments in call to l.logger.Debug
```

seems like go-logging changed their API. I will have to update the other repos too.

**Comment by xh3b4sd** [comment]
We needed to fix this already twice in the past. Can we prevent needing to fix it the fourth time?

**Comment by zeisss** [comment]
did we? well, thats part of the update process when using software. We could just quit using libs that have no API commitment

**Comment by zeisss** [comment]
we probably also should read the README and use the proper import paths: https://github.com/op/go-logging/commit/f9dfb79d4f4eb950e6bb3ca5660e3c31cac8f02c

**Comment by zeisss** [comment]
I will change the PR to use the gopkg.in path.

**Comment by xh3b4sd** [comment]
The latter one would be a good start.

**Pull request closed without merging**
