### PR TITLE
Use gopkg.in/go-logging.v1 for go-logging

### PR DESCRIPTION
**Pull request by zeisss**
Superseeds #5 - lets use gopkg.in for go-logging

### CODE REVIEW

**Comment by zeisss** [comment]
ping @giantswarm/cena

**Comment by xh3b4sd** [comment]
What benefit does this bring?

**Comment by zeisss** [comment]
gopkg.in is a helper that provides you with a way to import branches instead of `master`. The go-logging guys did a `v1` branch before breaking the API and this will stay compatible until they are actually done with v2

**Comment by xh3b4sd** [comment]
Seems legit. LGTM

**Pull request merged**
